<?php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

// Load Composer's autoloader
$autoloadPath = __DIR__ . '/../vendor/autoload.php';
if (!file_exists($autoloadPath)) {
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Server Error: Composer dependencies not installed (autoload.php not found).']);
    exit;
}
require_once $autoloadPath;

// --- Load Configuration ---
// This file contains sensitive information and should NOT be committed to version control.
require_once __DIR__ . '/config.php';

use MailerSend\MailerSend;
use MailerSend\Helpers\Builder\Recipient;
use MailerSend\Helpers\Builder\EmailParams;

// Use the API Key from the configuration file.
$apiKey = MAILERSEND_API_KEY;
$senderEmail = 'info@trial-z3m5jgrd6pogdpyo.mlsender.net'; // This must be a verified sender from your MailerSend account
$senderName = 'Seatlify';

// Get the POST data from the frontend
$requestBody = file_get_contents('php://input');
$data = json_decode($requestBody, true);

if (!$data || !isset($data['to']) || !filter_var($data['to'], FILTER_VALIDATE_EMAIL)) {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'Invalid or missing recipient email.']);
    exit;
}

$recipientEmail = $data['to'];
$eventTitle = isset($data['eventTitle']) ? htmlspecialchars($data['eventTitle']) : 'Your Event';
$eventDate = 'Awaiting Date';
if (isset($data['eventDate'])) {
    $timestamp = strtotime($data['eventDate']);
    if ($timestamp !== false) {
        $eventDate = date("F j, Y, g:i a", $timestamp);
    }
}
$type = isset($data['type']) ? $data['type'] : 'ticket';
$link = isset($data['link']) ? $data['link'] : '#';
$customHtml = isset($data['ticket_html']) ? $data['ticket_html'] : null;

// --- Email Content ---
if ($type === 'invitation') {
    $subject = "You are invited to " . $eventTitle;
    $htmlContent = "
        <h1>You're Invited!</h1>
        <p>Hello,</p>
        <p>You have been invited to <strong>{$eventTitle}</strong>.</p>
        <p><strong>When:</strong> {$eventDate}</p>
        <p>Please click the link below to view your invitation and RSVP:</p>
        <p><a href='{$link}' style='display:inline-block; padding:10px 20px; background-color:#0d6efd; color:#fff; text-decoration:none; border-radius:5px;'>View Invitation</a></p>
        <p><small>Or copy this link: {$link}</small></p>
        <br>
        <p>Best regards,</p>
        <p>The Seatlify Team</p>
    ";
    $textContent = "You are invited to {$eventTitle} on {$eventDate}. View your invitation here: {$link}";
} else {
    // Default: Ticket Confirmation
    $subject = "Your Ticket for " . $eventTitle;
    
    if ($customHtml) {
        // Use the custom HTML generated by the frontend (includes QR code)
        $htmlContent = $customHtml;
        $textContent = "Your Ticket for {$eventTitle} is confirmed. Please view this email in an HTML-compatible client to see your ticket.";
    } else {
        $htmlContent = "
            <h1>Your Ticket is Confirmed!</h1>
            <p>Hello,</p>
            <p>Thank you for registering. Here are your event details:</p>
            <ul>
                <li><strong>Event:</strong> {$eventTitle}</li>
                <li><strong>Date:</strong> {$eventDate}</li>
            </ul>
            <p>We look forward to seeing you there!</p>
            <br>
            <p>Best regards,</p>
            <p>The Seatlify Team</p>
        ";
        $textContent = "Your Ticket is Confirmed! Hello, Thank you for registering. Here are your event details: Event: {$eventTitle}, Date: {$eventDate}. We look forward to seeing you there! Best regards, The Seatlify Team";
    }
}

try {
    $mailersend = new MailerSend(['api_key' => $apiKey]);

    $recipients = [
        new Recipient($recipientEmail, 'Guest'),
    ];

    $emailParams = (new EmailParams())
        ->setFrom($senderEmail)
        ->setFromName($senderName)
        ->setRecipients($recipients)
        ->setSubject($subject)
        ->setHtml($htmlContent)
        ->setText($textContent);

    $mailersend->email->send($emailParams);

    echo json_encode(['success' => true, 'message' => 'Email sent successfully.']);
} catch (\Throwable $e) {
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Email Error: ' . $e->getMessage()]);
}
?>